version: '3.8'
services:
  localstack-napoleon:
    hostname: localstack
    image: localstack/localstack:1.0
    ports:
      - '4566:4566'
      - '8081:8080'
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - LOG_LEVEL=ERROR
      - DEBUG=1
    networks:
      - backend

  napoleon:
    hostname: napoleon
    depends_on:
      - localstack-napoleon
    build:
      context: .
      dockerfile: Localstack.dockerfile
    container_name: napoleon
    ports:
      - 4215:4215
    networks:
      - backend

networks:
  backend:
    driver: bridge


