version: '3.6'
services:
  localstack-napoleon:
    image: localstack/localstack:1.0
    ports:
      - '4566:4566'
      - '8081:8080'
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - LOG_LEVEL=ERROR
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './tmp/localstack:/var/lib/localstack'

